spring.datasource.url=jdbc:postgresql://ep-round-fog-aipg9sz6-pooler.c-4.us-east-1.aws.neon.tech/CoAgent4U?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_7TD3syCVdpeE

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000