spring.datasource.url=jdbc:postgresql://ep-crimson-credit-airhrjj7-pooler.c-4.us-east-1.aws.neon.tech:5432/CoAgent4U?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1NhOTH5poMEk

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000