package com.coagent4u.coordination.domain;

import java.util.Objects;

import com.coagent4u.shared.AgentId;
import com.coagent4u.shared.TimeSlot;

/**
 * Value object representing the proposed meeting details generated by
 * ProposalGenerator.
 */
public record MeetingProposal(
        String proposalId,
        String coordinationIdStr, // raw UUID string for the coordination
        AgentId requesterAgentId,
        AgentId inviteeAgentId,
        TimeSlot suggestedTime,
        int durationMinutes,
        String title,
        String timezone) {
    public MeetingProposal {
        Objects.requireNonNull(proposalId, "proposalId must not be null");
        Objects.requireNonNull(coordinationIdStr, "coordinationIdStr must not be null");
        Objects.requireNonNull(requesterAgentId, "requesterAgentId must not be null");
        Objects.requireNonNull(inviteeAgentId, "inviteeAgentId must not be null");
        Objects.requireNonNull(suggestedTime, "suggestedTime must not be null");
        Objects.requireNonNull(title, "title must not be null");
        Objects.requireNonNull(timezone, "timezone must not be null");
        if (durationMinutes <= 0)
            throw new IllegalArgumentException("durationMinutes must be > 0");
    }
}
